image: "b.gcr.io/kuar/etcd:2.2.0"
cluster_token: "cluster0"
cloud_provider: "aws"
members:
  - name: "etcd0"
    advertise_client_urls: "http://10.0.0.1:2379"
    initial_advertise_peer_urls: "http://10.0.0.1:2380"
    data_volume_id: "vol-1234data0"
    wal_volume_id: "vol-1234wal0"
  - name: "etcd1"
    advertise_client_urls: "http://10.0.0.2:2379"
    initial_advertise_peer_urls: "http://10.0.0.2:2380"
    data_volume_id: "vol-1234data1"
    wal_volume_id: "vol-1234wal1"
  - name: "etcd2"
    advertise_client_urls: "http://10.0.0.2:2379"
    initial_advertise_peer_urls: "http://10.0.0.2:2380"
    data_volume_id: "vol-1234data2"
    wal_volume_id: "vol-1234wal2"
