image: "b.gcr.io/kuar/etcd:2.2.0"
cluster_token: "cluster0"
cloud_provider: "gce"
members:
  - name: "etcd0"
    advertise_client_urls: "http://10.0.0.1:2379"
    initial_advertise_peer_urls: "http://10.0.0.1:2380"
    data_volume_id: "etcd-0-data"
    wal_volume_id: "etcd-0-wal"
  - name: "etcd1"
    advertise_client_urls: "http://10.0.0.2:2379"
    initial_advertise_peer_urls: "http://10.0.0.2:2380"
    data_volume_id: "etcd-1-data"
    wal_volume_id: "etcd-1-wal"
  - name: "etcd2"
    advertise_client_urls: "http://10.0.0.2:2379"
    initial_advertise_peer_urls: "http://10.0.0.2:2380"
    data_volume_id: "etcd-2-data"
    wal_volume_id: "etcd-2-wal"
